// Generated by CoffeeScript 1.12.6
(function() {
  window.start = function(form) {
    var bulls, comparision, composition, cows, input1, input_array, random_array, valid;
    input1 = form.digit.value;
    random_array = [];
    bulls = 0;
    cows = 0;
    valid = function(callback) {
      callback();
    };
    valid(function() {
      if (input1.match(/[0-9]{4}/)) {
        alert(input1);
      } else {
        alert("Wrong digit, try again");
        location.reload();
      }
    });
    composition = function(callback) {
      random_array = callback();
      alert(random_array);
    };
    composition(function() {
      var i, k, number;
      for (i = k = 0; k <= 3; i = ++k) {
        number = Math.random() * 9;
        number = number.toFixed(0);
        random_array.push(number);
      }
      return random_array;
    });
    input_array = input1.split('');
    alert(input_array);
    comparision = function(callback) {
      var answer, answer_confirm;
      answer = callback();
      if (answer.localeCompare("Win") === 0) {
        answer_confirm = confirm("You won! Wont to play again?");
        if (answer_confrim === 1) {
          return location.reload();
        } else {
          return window.close();
        }
      }
    };
    return;
    comparision(function() {
      var i, j, k, l;
      for (i = k = 0; k <= 3; i = ++k) {
        for (j = l = 0; l <= 3; j = ++l) {
          if (random_array[i] === input_array[j] && i === j) {
            bulls++;
          }
          if (random_array[i] === input_array[j] && i !== j) {
            cows++;
          }
        }
      }
      if (bulls === 4) {
        return "Win";
      }
    });
  };

}).call(this);
