// Generated by CoffeeScript 1.12.6
(function() {
  window.start = function(form) {
    var array, composition, input1;
    input1 = form.digit.value;
    array = [];

    /*do valid(do->
        (if(input1.match(/[0-9]4/))
            alert(input1)
        else 
            alert("Wrong digit, try again")
            location.reload())
    )
     */

    /*valid = (callback)->
    do callback.call(this)
    return
     */
    composition = function(callback) {
      return callback();
    };
    composition((function() {
      var i, j, number;
      for (i = j = 0; j <= 3; i = ++j) {
        number = Math.random() * 9;
        number = number.toFixed(0);
        array.push(number);
      }
      return array;
    })())();
  };

}).call(this);
